### ISSUE TITLE
vcgencmd installed and ssh user in 'video' group but not working.

### ISSUE THREAD

**Issue by chsims1** [eidottermihi/rpicheck#181]
Hi,

as the title says (/usr/bin/vcgencmd).  I can run 'sudo vcgencmd measure_temp' successfully from a ssh session, but app complains that vcgencmd can't be found or ssh user is not member of video group (both incorrect).

There is no log file as this distro (Volumio) runs with squashfs in RAM to minimise sd card writes. Presumably the absence of the log file wouldn't cause a failure??

**Comment by eidottermihi** [comment]
Hi,
the app runs vcgencmd without sudo. So you have to make sure your user has
the neccesary rights to execute vcgencmd without sudo.

Ian Sutherland <notifications@github.com> schrieb am So., 20. Mai 2018,
12:42:

**Comment by chsims1** [comment]
Ah ok, it failed without being sudo. I'll have a look when I can access the device. Thanks

**Comment by ChristopherRush** [comment]
Had a similar Issue with Volumio, when adding user to group video `sudo adduser volumio video` it did not resolve the issue. The culprit was `/dev/vchiq`.

`ls -l /dev/vchiq` returns:
`crw------- 1 root root 246, 0 Jun 17 22:13 /dev/vchiq`
Not:
`crw-rw---- 1 root video 246, 0 Jun 16 23:28 /dev/vchiq`

You need to run the following:
`sudo chmod g+rw /dev/vchiq`
`sudo chgrp video /dev/vchiq`
