### ISSUE TITLE
Querying for data overclocks CPU

### ISSUE THREAD

**Issue by CookiePLMonster** [eidottermihi/rpicheck#188]
It seems like raspi-check is connecting to the pi to query data, then disconnects. Connecting seems to add enough overhead for Raspberry Pi (I tested on 3B+, but may also apply to others) to overclock (with CPU governor set to `ondemand`). Because of that, even when idling I see CPU freq as 1400MHz and not 600MHz.

I also observe the same if I query for CPU speeds on my own with a command. Observe:

Main raspi-check screen:
![screenshot_2018-12-06-18-06-38](https://user-images.githubusercontent.com/7947461/49602999-4009fe80-f98a-11e8-94a8-d1855cf9b428.png)

`cat` for `scaling_cur_freq`, without any delays:
![screenshot_2018-12-06-18-06-45](https://user-images.githubusercontent.com/7947461/49603006-49936680-f98a-11e8-8028-802f0fb6f809.png)

`sleep` added before `cat`:
![screenshot_2018-12-06-18-07-19](https://user-images.githubusercontent.com/7947461/49603008-4b5d2a00-f98a-11e8-923c-0dc35f6ad8d8.png)

It seems like it'd be easily resolved by just waiting a bit after estabilishing connection and before querying for data.

Since it may be relevant: I am authenticated with a password (albeit I want to replace it with a key eventually), rpi is connected over WiFi (in case it makes a difference to connection overhead).

EDIT:
Authentication with a SSH key gives same results.

**Comment by eidottermihi** [comment]
As you have said correctly, the CPU "overclicking" is caused by opening the SSH connection and querying the data. 
Adding more timeouts would further increase the querying time (which is already quite long) - so I'm against that.

Maybe there are other solutions (like "average clock rate for last 5 minutes") which would work better for the purpose. If you know such other solutions, I would be up for a new consideration.
